apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.client.host }},{{ $.Values.server.host }}"
spec:
  tls:
  - hosts:
    - {{ $.Values.client.host }}
    - {{ $.Values.server.host }}
    secretName: "{{ .Chart.Name }}-tls"
  rules:
  - host: {{ $.Values.client.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "{{ .Chart.Name }}-client"
            port:
              number: {{ $.Values.client.port }}
  - host: {{ $.Values.server.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "{{ .Chart.Name }}-server"
            port:
              number: {{ $.Values.server.port }}
