apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-server-service"
  labels:
    app: {{ .Chart.Name }}-server
  annotations:
    kubernetes.digitalocean.com/firewall-managed: "false"
    kubernetes.tim-ings.com/domain: "api.loot.arwic.io"
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-server
  ports:
    - name: http
      port: {{ $.Values.server.port }}
      nodePort: {{ $.Values.server.nodePort }}
